[package]
name = "simplifid-cache"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11"
actix-web = "4.4"
tokio = { version = "1" }
futures = { version = "0.3" }
env_logger = "0.10"
